MapName: LCAS
Regions: [
      {
      name: 'kitchen', 
      points: [1.51, -1.01, 4.52, -1.01, 4.52, 2.14, 1.51, 2.14],
      subregions: [
          {name: 'kitchen - fridge', points: [1.51, -1.01, 4.52, -1.01, 4.52, 0.46, 1.51, 0.46] }, 
          {name: 'kitchen - coffee', points: [1.51,  0.46, 4.52,  0.46, 4.52, 2.14, 1.51, 2.14] }                  
                  ] 
      },
      {
      name: 'entrance corridor', 
      points: [-2.7,2.23,4.52,2.23,4.52,4.98,-2.7,4.98]    
      },
      {
      name: 'bathroom corridor', 
      points: [-0.22,-1.23,1.53,-1.23,1.53,2.1,-0.22,2.1],    
      },
      {
      name: 'workzone corridor', 
      points: [-0.18, 5.01, 1.0, 5.01, 1.0, 13.86, -0.18, 13.86],    
      },
      {
      name: 'workzone G', 
      points: [-5.04,5.0,-0.2,5.0,-0.2,8.72,-5.04,8.72],    
      },
      {
      name: 'workzone P', 
      points: [1.06,5.09,4.81,5.09,4.81,8.83,1.06,8.83],    
      },
      {
      name: 'workzone Y', 
      points: [-4.97,8.72,-0.14,8.72,-0.14,13.82,-4.97,13.82],    
      },
      {
      name: 'workzone T', 
      points: [1.11,8.87,5.13,8.87,5.13,13.82,1.11,13.82],    
      },
      {
      name: 'entrance', 
      points: [-5.13,2.23,-2.7,2.23,-2.7,4.98,-5.13,4.98],    
      },      
      {
      name: 'lounge', 
      points: [-5.13,-1.29,-0.27,-1.29,-0.27,2.23,-5.13,2.23],
      subregions: [
          { name: 'lounge - sofas', points: [-5.13,-1.29,-2.52,-1.29,-2.52,2.23,-5.13,2.23] }, 
          { name: 'lounge - tv', points: [-2.52,-1.29,-0.27,-1.29,-0.27,2.23,-2.52,2.23] }                  
                  ] 
      }
    ]
