{mmap: {numberOfSubMaps: 1, zoi: {submap_0: {bathroomcorridor_0: [submap_0, bathroomcorridor,
          -0.22, -1.23], bathroomcorridor_1: [submap_0, bathroomcorridor, 1.53, -1.23],
        bathroomcorridor_2: [submap_0, bathroomcorridor, 1.53, 2.1], bathroomcorridor_3: [
          submap_0, bathroomcorridor, -0.22, 2.1], entrance_0: [submap_0, entrance,
          -5.13, 2.23], entrance_1: [submap_0, entrance, -2.7, 2.23], entrance_2: [
          submap_0, entrance, -2.7, 4.98], entrance_3: [submap_0, entrance, -5.13,
          4.98], entrancecorridor_0: [submap_0, entrancecorridor, -2.7, 2.23], entrancecorridor_1: [
          submap_0, entrancecorridor, 4.52, 2.23], entrancecorridor_2: [submap_0,
          entrancecorridor, 4.52, 4.98], entrancecorridor_3: [submap_0, entrancecorridor,
          -2.7, 4.98], kitchen_0: [submap_0, kitchen, 1.51, -1.01], kitchen_1: [submap_0,
          kitchen, 4.52, -1.01], kitchen_2: [submap_0, kitchen, 4.52, 2.14], kitchen_3: [
          submap_0, kitchen, 1.51, 2.14], kitchen_coffee_0: [submap_0, kitchen_coffee,
          1.51, 0.46], kitchen_coffee_1: [submap_0, kitchen_coffee, 4.52, 0.46], kitchen_coffee_2: [
          submap_0, kitchen_coffee, 4.52, 2.14], kitchen_coffee_3: [submap_0, kitchen_coffee,
          1.51, 2.14], kitchen_fridge_0: [submap_0, kitchen_fridge, 1.51, -1.01],
        kitchen_fridge_1: [submap_0, kitchen_fridge, 4.52, -1.01], kitchen_fridge_2: [
          submap_0, kitchen_fridge, 4.52, 0.46], kitchen_fridge_3: [submap_0, kitchen_fridge,
          1.51, 0.46], lounge_0: [submap_0, lounge, -5.13, -1.29], lounge_1: [submap_0,
          lounge, -0.27, -1.29], lounge_2: [submap_0, lounge, -0.27, 2.23], lounge_3: [
          submap_0, lounge, -5.13, 2.23], lounge_sofas_0: [submap_0, lounge_sofas,
          -5.13, -1.29], lounge_sofas_1: [submap_0, lounge_sofas, -2.52, -1.29], lounge_sofas_2: [
          submap_0, lounge_sofas, -2.52, 2.23], lounge_sofas_3: [submap_0, lounge_sofas,
          -5.13, 2.23], lounge_tv_0: [submap_0, lounge_tv, -2.52, -1.29], lounge_tv_1: [
          submap_0, lounge_tv, -0.27, -1.29], lounge_tv_2: [submap_0, lounge_tv, -0.27,
          2.23], lounge_tv_3: [submap_0, lounge_tv, -2.52, 2.23], workzoneG_0: [submap_0,
          workzoneG, -5.04, 5.0], workzoneG_1: [submap_0, workzoneG, -0.2, 5.0], workzoneG_2: [
          submap_0, workzoneG, -0.2, 8.72], workzoneG_3: [submap_0, workzoneG, -5.04,
          8.72], workzoneP_0: [submap_0, workzoneP, 1.06, 5.09], workzoneP_1: [submap_0,
          workzoneP, 4.81, 5.09], workzoneP_2: [submap_0, workzoneP, 4.81, 8.83],
        workzoneP_3: [submap_0, workzoneP, 1.06, 8.83], workzoneT_0: [submap_0, workzoneT,
          1.11, 8.87], workzoneT_1: [submap_0, workzoneT, 5.13, 8.87], workzoneT_2: [
          submap_0, workzoneT, 5.13, 13.82], workzoneT_3: [submap_0, workzoneT, 1.11,
          13.82], workzoneY_0: [submap_0, workzoneY, -4.97, 8.72], workzoneY_1: [
          submap_0, workzoneY, -0.14, 8.72], workzoneY_2: [submap_0, workzoneY, -0.14,
          13.82], workzoneY_3: [submap_0, workzoneY, -4.97, 13.82], workzonecorridor_0: [
          submap_0, workzonecorridor, -0.18, 5.01], workzonecorridor_1: [submap_0,
          workzonecorridor, 1.0, 5.01], workzonecorridor_2: [submap_0, workzonecorridor,
          1.0, 13.86], workzonecorridor_3: [submap_0, workzonecorridor, -0.18, 13.86]}}}}
