MapName: ROBOSOFT
Regions: [
      {
      name: 'kitchen', 
      points: [  4.00, 5.83, 7.58, 5.83, 7.58, 7.13, 4.00, 7.13 ]       
      },
      {
      name: 'lounge', 
      points: [  6.22, 1.3, 8.3 , 1.3,   8.3, 4.16, 6.22, 4.16 ]    
      }
    ]
