global_frame: /map
robot_base_frame: thorvald_001/base_link

footprint: [[1, 1], [1, -1], [-1, -1], [-1, 1]]

map_layer:
  map_topic: /map

global_inflation_layer:
  inflation_radius: 1
  cost_scaling_factor: 5.0

local_inflation_layer:
  inflation_radius: 1
  cost_scaling_factor: 5.0

obstacle_layer:
  max_obstacle_height: 2
  obstacle_range: 5
  raytrace_range: 3.0

  unknown_threshold: 6
  mark_threshold: 0

  track_unknown_space: true

  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: thorvald_001/hokuyo, data_type: LaserScan, topic: thorvald_001/vel/scan, marking: false, clearing: false}

global_obstacle_layer:
  max_obstacle_height: 2.0
  obstacle_range: 5
  raytrace_range: 3.0

  unknown_threshold: 6
  mark_threshold: 0

  track_unknown_space: true

  observation_sources: laser_scan_sensor
  laser_scan_sensor: {sensor_frame: thorvald_001/hokuyo, data_type: LaserScan, topic: thorvald_001/vel/scan_filtered, marking: true, clearing: true}
